### ISSUE TITLE
policy_lookup parameter in the cas_policy_plot

### ISSUE THREAD

**Issue by g413164351** [sisl/CollisionAvoidancePOMDPs.jl#1]
Dear mossr,
Could you please let me know what should be passed as the policy_lookup parameter in the cas_policy_plot function in plotting.jl?
Thank you for your assistance.

**Comment by mossr** [comment]
The `policy_lookup` parameter was originally intended for the [BetaZero](https://github.com/sisl/BetaZero.jl) policy object, which has a `surrogate` field. You'd have to modify the `cas_policy_plot` function so that the 3 lines that use `policy_lookup` do not rely on the `policy.surrogate` field: https://github.com/sisl/CollisionAvoidancePOMDPs.jl/blob/274a1d620d7dc670d08d3c9986b3d74630b8ae9d/src/plotting.jl#L188-L208

The point of the `policy_lookup` is to get either an action (with `plot_type = PolicyPlot`), the value (with `plot_type = ValuePlot`) or the failure probability (with `plot_type = PfailPlot`, using [ConstrainedZero](https://github.com/sisl/ConstrainedZero.jl)).

If you want to plot the action from the input `policy`, you can define `policy_lookup = POMDPs.action` and then modify this line
https://github.com/sisl/CollisionAvoidancePOMDPs.jl/blob/274a1d620d7dc670d08d3c9986b3d74630b8ae9d/src/plotting.jl#L204 and change it to
```julia
z = policy_lookup(policy, b)
```

If instead you want to see the _value_ of your policy, then you can set `policy_lookup = POMDPs.value` and `plot_type = ValuePlot` and then change
https://github.com/sisl/CollisionAvoidancePOMDPs.jl/blob/274a1d620d7dc670d08d3c9986b3d74630b8ae9d/src/plotting.jl#L189
to be
```julia
z = policy_lookup(policy, b)
```

I'll likely change that function so that it does not rely on the BetaZero or ConstrainedZero policy type.

**Comment by g413164351** [comment]
Thank you so much for your quick response and assistance!
